#
# Makefile for misc devices that really don't fit anywhere else.
#
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/mt6580/include/mach
ccflags-y += -I$(srctree)/drivers/misc/mediatek/leds/mt6580

obj-y				+= leds_strobe.o
