ccflags-y += -I$(srctree)/drivers/misc/mediatek/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
#ccflags-y += -I$(srctree)/drivers/misc/mediatek/step_counter

obj-y	:=  bmi160_acc.o

